version: '3.8'

services:
  app:
    build: .
    container_name: nestjs_app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - database

  database:
    image: postgres:15
    container_name: nestjs_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
